### ISSUE TITLE
Support controller inheritance

### ISSUE THREAD

**Issue by ghempton** [inossidabile/heimdallr-resource#3]
I would like to have a base controller from which other controllers inherit. This base controller would use the Heimdallr::Resource mixin.

The current implementation prevents this as `class_name` will be set based on the base controllers name. CanCan gets around this by using params[:controller] instead of the class name. An alternative implementation could use the Class inherited hook to change the resource name in any subclasses.

**Comment by AlexanderPavlenko** [comment]
Is this issue still actual? Can you please provide some examples?

**Comment by inossidabile** [comment]
It might not be actual for issuer but I believe it should be implemented.

**Comment by AlexanderPavlenko** [comment]
@inossidabile I believe it's already fixed somehow. We already “have base controller from which other controllers inherit”, and pass `{:resource => :account}` option to `load_and_authorize_resource` in descendants.

**Comment by AlexanderPavlenko** [comment]
`options[:resource] ||= controller_class.name.sub(/Controller$/, '').singularize.underscore` 
[this](https://github.com/roundlake/heimdallr-resource/blob/master/lib/heimdallr/resource_implementation.rb#L16) looks inheritance-awared too

**Comment by inossidabile** [comment]
Okay. Let's close it then.

**Comment by sh-ft** [comment]
I think what @ghempton is talking about is putting `load_and_authorize_resource` (without `:resource` option specified) not in subcontrollers, but in the base controller, which would load a resource based on a current (sub-) controller name. This, indeed, doesn't work. I, however, can't think of a good reason to do that, so an example would be great.

**Comment by sh-ft** [comment]
What I would actually like to have is the ability to load a parent resource in a base controller and then have subcontrollers load child resources through that parent resource.

**Comment by AlexanderPavlenko** [comment]
How can you have, according to REST, two different resources for one controller?
Or did you mean controllers' nesting in routes, not the class inheritance? This already cay be done using `:through => 'parent_resource'` option.

**Comment by sh-ft** [comment]
Both nesting and inheritance.
Here's an example: https://gist.github.com/4235205.
The `BasePostsController` isn't, of course, a real controller. It just holds the common code for subclasses, like `ApplicationController`.

Now that I think of it, though, that can also be done with a module instead of a base class.

**Comment by AlexanderPavlenko** [comment]
Totally insane and meaningless inheritance in this example. Just `include Heimdallr::Resource` in `ApplicationController` and it'll be the same thing.

**Comment by sh-ft** [comment]
And what about `load_and_authorize_resource :resource => :post` and a `before_filter`, possibly with lots of code in it? We can't include that in `ApplicationController`, because we also have other, unrelated to posts, controllers. And we can't include that code in each of the post subcontrollers, because that would be repeating ourselves.
